### ISSUE TITLE
Splash Screen beim Start anzeigen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#107]
Als Benutzer/in möchte ich beim Start von Plotify einen Splash Screen angezeigt bekommen, damit ich sehe, dass die Anwendung gestartet wird.

**Akzeptanzkriterien**
- [x] Der Splash Screen soll angezeigt werden, bevor das Hauptfenster geladen wird.
- [x] Der Splash Screen soll in dem Moment ausgeblendet werden, in dem das Hauptfenster geöffnet wird.
- [x] Das Hauptfenster soll angezeigt werden, sobald die Benutzeroberfläche geladen worden ist.

**Comment by SebastianSchmidt** [comment]
Erfolgreich getestet unter:
- Windows 7
- Ubuntu 17.04
- Linux Mint 18.1
- elementary OS 0.4

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Kannst du die Anzeige des Splash Screens unter Windows 10 und macOS testen?

**Comment by itsJASPERr** [comment]
Erfolgreich getestet unter:
* macOS High Sierra 10.13.1
* Windows 10 Version 1709
