### ISSUE TITLE
Zuletzt geöffnete Geschichten anzeigen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#108]
Als Schriftsteller/in möchte ich eine Liste der zuletzt geöffneten Geschichten angezeigt bekommen, wenn ich keine Geschichte geöffnet habe, damit ich schnell meine aktuellen Geschichten öffnen kann.

**Akzeptanzkriterien**
- [x] Die zuletzt geöffneten Geschichten sollen sortiert in einer Liste angezeigt werden (zuletzt geöffnet zuerst).
- [x] Für jede Geschichte soll der Dateiname ohne die Dateiendung (.story) angezeigt werden.
- [x] Zu jeder Geschichte soll der Pfad des Verzeichnisses angezeigt werden, in dem die Datei gespeichert ist.
- [x] Die Liste der zuletzt geöffneten Geschichten soll automatisch aktualisiert werden, wenn in anderen Fenstern Geschichten geöffnet werden, während die Liste in einem Fenster angezeigt wird.
- [x] Wenn es keine zuletzt geöffneten Geschichten gibt, soll ein kurzer Text angezeigt werden, der darauf hinweist, dass an dieser Stelle zukünftig zuletzt geöffnete Geschichten angezeigt werden.
- [x] Wenn eine Geschichte innerhalb von Plotify geöffnet wird, soll dies unter Windows und macOS auch dem Betriebssystem mitgeteilt werden ([app.addRecentDocument(path)](https://electronjs.org/docs/api/app#appaddrecentdocumentpath-macos-windows)).
- [x] Es sollen maximal die letzten 25 Geschichten gespeichert werden. Wenn bereits 25 Geschichten gespeichert sind und eine weitere Geschichte hinzugefügt wird, soll die ältestete Geschichte (am längsten nicht mehr geöffnet) aus der Liste entfernt werden.
- [x] Beim automatischen Entfernen von Geschichten soll die Logik aus #113 verwendet werden.
- [x] Beim automatischen Entfernen von Geschichten sollen die Einschränkungen aus #109 beachtet werden.

**Comment by SebastianSchmidt** [comment]
Erfolgreich getestet unter:
- Windows 7
- Ubuntu 17.10
- Linux Mint 18.1
- elementary OS 0.4

**Comment by itsJASPERr** [comment]
🎉
