### ISSUE TITLE
Zuletzt geöffnete Geschichten im Verzeichnis anzeigen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#114]
Als Schriftsteller/in möchte ich mir die Datei einer der zuletzt geöffneten Geschichten im jeweiligen Verzeichnis im Dateimanager anzeigen lassen können, damit ich die Datei der Geschichte schnell wiederfinden kann.

Siehe #108

**Comment by SebastianSchmidt** [comment]
Erfolgreich getestet unter:
- Windows 7
- Ubuntu 17.10
- Linux Mint 18.1
- elementary OS 0.4

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Kannst du das Öffnen von zuletzt geöffneten Geschichten im Dateimanager unter Windows 10 und macOS testen?

**Comment by itsJASPERr** [comment]
Unter macOS funktioniert es.

**Comment by itsJASPERr** [comment]
Ebenfalls unter Windows 10
