### ISSUE TITLE
Datei aus Dateimanager öffnen schlägt fehl

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#116]
1. Geschichte aus Dateimanager öffnen
2. Plotify öffnet sich
3. Geschichte wird geöffnet
4. Fenster schließen (x; nicht Programm schließen)
5. Datei aus Dateimanager öffnen
6. Fehler

![image](https://user-images.githubusercontent.com/11521721/34009646-fcf97024-e109-11e7-9dde-f02c824d3e43.png)

**Comment by SebastianSchmidt** [comment]
Wenn das Hauptfenster geschlossen wird, wird die interne Referenz auf das Hauptfenster gelöscht:

**create-main-window.js:**
```javascript
  mainWindow.on('closed', () => {
    setMainWindow(null)
  })
```

Unter macOS wird jedoch die Anwendung nicht geschlossen, wenn das Hauptfenster geschlossen wurde:

**main.js:**
```javascript
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

Wenn nun eine Geschichte geöffnet werden soll, wird versucht, ein Signal an das Hauptfenster zu senden:

**main.js:**
```javascript
app.on('open-file', (event, path) => {
  event.preventDefault()
  if (loading) {
    macOsStoryPath = path
  } else {
    request(OPEN_STORY_REQUESTED, path)
  }
})
```

Da aber kein Hauptfenster mehr existiert, kommt es zu der oben beschriebenen Fehlermeldung.
Um den Fehler zu beheben muss in diesem Fall ein neues Hauptfenster initialisiert werden, bevor das Signal zum Öffnen der Geschichte gesendet wird.

**Comment by SebastianSchmidt** [comment]
Wir müssen auch an den Fall denken, dass eine weitere Geschichte geöffnet wird, während bereits eine geöffnet ist. Unter Windows und Linux wird die Geschichte in einem neuen Fenster mit einem eigenem Prozess geöffnet. Unter macOS wird die Geschichte in demselben Fenster geöffnet und die alte Geschichte geschlossen.

**Comment by SebastianSchmidt** [comment]
Eventuell sollten wir Plotify zu einer Single-Instance-Application machen (app.makeSingleInstance(callback)).

**Comment by SebastianSchmidt** [comment]
Der Fehler wird im Rahmen des Tickets #118 behoben werden.

**Comment by SebastianSchmidt** [comment]
Der Fehler wurde im Rahmen des Tickets #118 behoben.
