### ISSUE TITLE
Mehrere Geschichten in einer Instanz öffnen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#118]
Aktuell muss für jede Geschichte eine eigene Instanz von Plotify gestartet werden. Zukünftig soll immer nur eine Instanz von Plotify gestartet sein, die mehrere Geschichten in mehreren Fenstern anzeigen kann. Das spart Ressourcen auf den Computern der Anwender.

**Aufgaben:**
- [x] Die IPC-Nachrichten müssen abhängig von dem jeweiligen Absenderfenster behandelt werden.
- [x] Es müssen mehrere Geschichten geöffnet und den jeweiligen Fenster zugeordnet werden können.
- [x] Das Event `open-file` muss ein neues Fenster mit der übergebenen Geschichte öffnen.
- [x] Der Callback der Funktion `app.makeSingleInstance` muss ein neues Fenster mit der übergebenen Geschichte öffnen.
- [x] Beim Starten der Anwendung müssen alle `open-file`-Events und Callbacks der Funktion `app.makeSingleInstance` während das Backend initialisiert wird gespeichert und anschließend wie oben beschrieben nachträglich durchgeführt werden. Es soll keine Geschichte doppelt geöffnet werden.
- [x] Wenn der Pfad zu einer Datei als Argument an die Anwendung übergeben wurde, soll der Pfad gespeichert und wie oben beschrieben geöffnet werden.
- [x] Der Splash Screen soll immer dann angezeigt werden wenn ein neues Fenster geöffnet wird.
- [x] Beim Starten der Anwendung soll der Splash Screen von Anfang an angezeigt werden.
- [x] Es soll maximal ein Splash Screen angezeigt werden. Wenn mehrere Fenster parallel geladen werden soll trotzdem nur ein Splash Screen angezeigt werden.
- [x] Wenn eine Geschichte bereits geöffnet ist, fokussiere das entsprechende Fenster. Eine Geschichte soll nicht doppelt geöffnet werden.
- [x] Wenn bereits ein Fenster ohne Geschichte geöffnet ist, soll kein neues Fenster geöffnet werden, wenn der Benutzer die Anwendung startet, sondern das entsprechende Fenster soll fokussiert werden.
- [x] Wenn eine Datei aus dem Dateimanager geöffnet wird und dabei ein Fehler auftritt, soll kein Fenster erzeugt sondern nur ein Dialog mit der Fehlermeldung angezeigt werden.
- [x] Die Menüeinträge wirken sich immer auf das jeweils verbundene Fenster aus.
- [x] Wenn die Geschichte bereits in einem anderen Fenster geöffnet ist, soll das Menü "Geschichte öffnen" das andere Fenster fokussieren statt die Geschichte erneut in einem anderen Fenster zu öffnen.
- [x] Wenn bereits eine Geschichte geöffnet ist, sollen die Menüeinträge "Neue Geschichte" oder "Geschichte öffnen" neue Fenster öffnen.
- [x] Geschichte schließen, wenn das dazugehörige Fenster geschlossen wird.
- [x] Refactoring: Save state & reload
- [x] Refactoring: Alte Dateien und alten Code entfernen

**Comment by SebastianSchmidt** [comment]
Die Umsetzung dieses Tickets sollte auch den Fehler #116 beheben.

**Comment by SebastianSchmidt** [comment]
In Ticket #119 wird der Fall behandelt, dass unter macOS kein Fenster geöffnet ist. In dieser Situation gibt es potentiell Probleme mit einigen Menüpunkten, die Aktionen in Bezug auf ein Fenster ausführen (z.B. Geschichte öffnen oder Über Plotify).

**Comment by SebastianSchmidt** [comment]
Erfolgreich getestet unter:
- Windows 7
- Ubuntu 17.04
- Linux Mint 18.1
- elementary OS 0.4

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Kannst du das Öffnen von mehreren Geschichten in verschiedenen Fenstern unter Windows 10 und macOS testen? (Siehe [Einschränkungen](https://github.com/plotify/plotify/issues/118#issuecomment-354605742))

**Comment by itsJASPERr** [comment]
Test **macOS**:
* Es war bisher nicht möglich mehrere Instanzen von Plotify zu öffnen
* Öffnen/Erstellen öffnet ein zweites Fenster
* Ist die Geschichte bereits offen, wird das Fenster fokussiert, _aber nicht in den Vordergrund gebracht_
* Nach erster Neuinstallation trat ein Berechtigungsfehler beim Öffnen aus dem Dateimanager auf, dieser ist nun leider nicht mehr zu reproduzieren. 
* _Einzelne Fenster können nicht via ⌘W geschlossen werden_
* _⌘Q schließt alle Fenster, jedoch nicht die Instanz_

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Im Rahmen des Meilensteins [v0.2.0-alpha.1](https://github.com/plotify/plotify/milestone/7) soll macOS noch nicht vollständig unterstützt werden. Im nächsten Meilenstein [v0.2.0-alpha.2](https://github.com/plotify/plotify/milestone/11) soll macOS vollständig unterstützt werden. Ich habe für die von dir gefundenen Fehler einzelne Tickets in diesem Meilenstein erstellt: #120, #123 und  #124.

**Comment by SebastianSchmidt** [comment]
Das Öffnen von Geschichten in verschiedenen Fenstern funktioniert unter Linux und Windows. Die Unterstützung von macOS wird in Meilenstein [v0.2.0-alpha.2](https://github.com/plotify/plotify/milestone/11) umgesetzt werden.
