### ISSUE TITLE
Windows-spezifisches Menü

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#122]
Siehe: [Windows Menu Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742392(v=vs.85).aspx)

- [x] Datei
  - [x] Neu...
  - [x] Öffnen...
  - [x] Zuletzt geöffnet (Untermenü: Eine Liste der zuletzt geöffneten Geschichten: #135)
  - [x] Schließen (#134)
  - [x] ---
  - [x] Beenden
- [x] Bearbeiten
  - [x] Ausschneiden
  - [x] Kopieren
  - [x] Einfügen
  - [x] ---
  - [x] Alles auswählen
- [x] Ansicht
  - [x] Vergrößern
  - [x] Verkleinern
  - [x] Standardgröße
  - [x] ---
  - [x] Nachtmodus
  - [x] --- 
  - [x] Vollbild
- [x] Fenster
  - [x] (Eine Liste aller geöffneten Fenster: #154)
- [x] Hilfe
  - [x] Über Plotify

**Comment by itsJASPERr** [comment]
@SebastianSchmidt Soll sich die Recently Opened Liste im Menü aktualisieren, wenn eine neue geöffnet wurde?

**Comment by SebastianSchmidt** [comment]
Ja. Dafür muss aber wahrscheinlich etwas mehr gemacht werden. Am besten erstellen wir dafür ein eigenes Issue.

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Ich habe ein entsprechendes Issue dafür angelegt: #135.

**Comment by itsJASPERr** [comment]
👍 denke auch, da ist etwas mehr nötig

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SebastianSchmidt** [comment]
Feature-Branch: [122-menu-bar-window](https://github.com/plotify/plotify/tree/122-menu-bar-windows)
