### ISSUE TITLE
Beim Beenden der Anwendung werden alle Fenster, aber nicht die Anwendung geschlossen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#123]
## Erwartetes Verhalten

1. Starte Plotify.
2. Öffne eine Geschichte.
3. Beende Plotify über "Plotify beenden" oder ⌘Q.
4. Die Geschichte und das Fenster werden geschlossen.
5. Plotify wird beendet.

## Tatsächliches Verhalten

1. Starte Plotify.
2. Öffne eine Geschichte.
3. Beende Plotify über "Plotify beenden" oder ⌘Q.
4. Die Geschichte und das Fenster werden geschlossen.
5. Plotify wird nicht beendet.

## Umgebung

- Plotify-Version: 0.2.0-alpha.4
- Betriebssystem: macOS 10.13.3

**Comment by itsJASPERr** [comment]
Dies scheint ein Problem mit Electron zu sein. Die Schnittstelle für das Beenden der Anwendung wird von Electron zur Verfügung gestellt. Verschiedene Electron-Prozesse werden ebenfalls nicht korrekt beendet.

**Comment by SebastianSchmidt** [comment]
Branch: [123-mac-os-quit-application](https://github.com/plotify/plotify/tree/123-mac-os-quit-application)

**Comment by SebastianSchmidt** [comment]
Branch: [123-mac-os-quit](https://github.com/plotify/plotify/tree/123-mac-os-quit)
