### ISSUE TITLE
Bereits geöffnete Geschichte wird fokussiert, aber nicht in den Vordergrund gebracht

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#124]
1. Öffne die Geschichte foo.story über `Ablage -> Öffnen...`
2. Öffne die Geschichte bar.story über `Ablage -> Öffnen...`
3. Fokussiere die Geschichte bar.story über `Ablage -> Öffnen...`
4. Öffne die Geschichte foo.story über `Ablage -> Öffnen...`

Dies soll das Fenster von foo.story fokussieren und in den Vordergrund bringen.
Aktuell wird das Fenster zwar fokussiert, aber nicht in den Vordergrund gebracht.

**Comment by itsJASPERr** [comment]
Meine Baustelle, weil macOS, oder?

**Comment by SebastianSchmidt** [comment]
Ja. Am besten recherchierst du als erstes, ob man unter macOS mit Electron den Fokus von Fenstern überhaupt steuern kann.

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Ich übernehme die Umsetzung dieses Tickets.

**Comment by SebastianSchmidt** [comment]
Branch: [124-mac-os-window-focus](https://github.com/plotify/plotify/tree/124-mac-os-window-focus)

**Comment by SebastianSchmidt** [comment]
Der Fehler tritt nicht auf, wenn der Fokus über das Fenster-Menü oder über Ablage->"Zuletzt geöffnet" geöffnet wird. Der Fehler tritt auf, wenn man die andere Geschichte über Ablage->Öffnen öffnet - also über ein Dialog-Fenster von macOS.

**Comment by SebastianSchmidt** [comment]
Möglicher Workaround:

```javascript
export const focusWindow = (window) => {
  const maximized = window.isMaximized()
  if (window.isMinimized()) {
    window.restore()
  }
  if (maximized) {
    window.maximize()
  }
  window.focus()

  if (!window.isAlwaysOnTop()) {
    window.setAlwaysOnTop(true)
    setTimeout(() => window.setAlwaysOnTop(false), 500)
  }
}
```

Über den Aufruf
