### ISSUE TITLE
Text mit Zeilenumbruch in einem Steckbrief wird abgeschnitten angezeigt

### ISSUE THREAD

**Issue by RebeccaRademacher** [plotify/plotify#132]
## Erwartetes Verhalten

1. Neue Geschichte mit beliebigem Namen erstellen.
2. Neuen Charakter mit beliebigem Namen erstellen.
3. Bearbeitenmodus für den Charakter aktivieren (Bearbeiten-Button).
4. In ein beliebiges Textfeld so viel Text eintragen, dass ein Zeilenumbruch entsteht.
5. Bearbeitenmodus beenden.
6. Bearbeitenmodus aktivieren.
7. Der zuvor eingetragene Text wird vollständig mit Zeilenumbruch dargestellt.

![Erwartetes Verhalten](https://user-images.githubusercontent.com/27628506/34741777-15fb8e8e-f584-11e7-8208-e4aed24e04b5.png)

## Tatsächliches Verhalten

1. Neue Geschichte mit beliebigem Namen erstellen.
2. Neuen Charakter mit beliebigem Namen erstellen.
3. Bearbeitenmodus für den Charakter aktivieren (Bearbeiten-Button).
4. In ein beliebiges Textfeld so viel Text eintragen, dass ein Zeilenumbruch entsteht.
5. Bearbeitenmodus beenden.
6. Bearbeitenmodus aktivieren.
7. Der zuvor eingetragene Text wird nach der ersten Zeile abgeschnitten, und ein Scrollbalken angezeigt.

![Tatsächliches Verhalten](https://user-images.githubusercontent.com/27628506/34741829-417c3e0a-f584-11e7-8374-9e82075541c4.png)

## Umgebung

- Plotify-Version: 0.2.0-alpha.1
- Betriebssystem: Ubuntu 16.04

**Comment by SebastianSchmidt** [comment]
Ich kann den Fehler unter den folgenden Betriebssystemen reproduzieren:
- Ubuntu 17.04
- Windows 7

**Comment by SebastianSchmidt** [comment]
Da der Fehler die Übersicht beim Bearbeiten des Steckbriefs beeinträchtigt, sollten wir den Fehler am besten im Zuge der Überarbeitung der Übergänge beim Bearbeiten der Steckbriefe korrigieren.

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Tritt der Fehler auch unter macOS auf?

**Comment by itsJASPERr** [comment]
Ergänzung: Der Fehler tritt scheinbar nur auf, wenn es sich um das einzige Feld in der Zeile handelt. Also nur dann, wenn im Ansichtsmodus das Feld breiter ist, als im Bearbeitungsmodus. In diesem Fall tritt es auf macOS auch auf. Sind zwei Felder nebeneinander gefüllt, sodass sich die Breite nicht ändert, tritt dieser Fehler nicht auf.

**Comment by itsJASPERr** [comment]
Ich schlage vor, für die Ansicht keine Inputfelder zu verwenden. Somit verändern sich nicht Breite und Inhalte der selben Komponente bein Modus-wechsel. @SebastianSchmidt was  meinst du?

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Hatten wir nicht sowieso überlegt, dass alle Eingabefelder immer die gleiche Breite haben sollen (also jedes Eingabefeld genau die Breite einer Spalte)? Dann würde sich die Breite der Felder auch nicht in den verschiedenen Modi verändern.

**Comment by itsJASPERr** [comment]
Dies würde zu einem Ungleichgewicht in der Ansicht führen, aber auch eine mögliche Lösung.

**Comment by SebastianSchmidt** [comment]
Ich werden den Fehler zunächst über den Workaround `overflow: hidden` beheben. Zu gegebener Zeit werde ich mir Material-UI nochmal genauer anschauen.

**Comment by SebastianSchmidt** [comment]
Branch: [132-bug-text-field-scrollbar](https://github.com/plotify/plotify/tree/132-bug-text-field-scrollbar)
