### ISSUE TITLE
Text im letzten Feld des Steckbriefes wird abgeschnitten

### ISSUE THREAD

**Issue by RebeccaRademacher** [plotify/plotify#139]
## Erwartetes Verhalten

1. Ein Steckbrief wird aufgerufen.
2. Es wird nach unten gescrollt.
3. Der komplette Text ist sichtbar.

![Erwartetes Verhalten](https://user-images.githubusercontent.com/27628506/35182890-1645b552-fddd-11e7-8181-0369a7d62e30.png)

## Tatsächliches Verhalten

1. Ein Steckbrief wird aufgerufen.
2. Es wird nach unten gescrollt.
3. Der Text im letzten Feld ist nach unten hin abgeschnitten.
4. (Fährt man dem Mauszeiger über das Textfeld erscheint der ganze Text.)

![Tatsachliches verhalten](https://user-images.githubusercontent.com/27628506/35182936-bd62a958-fddd-11e7-80a8-bbaf34044389.png)

## Weitere Infos

Den Fehler konnte ich nicht reproduzieren. 
Nachdem ich die Version Plotify 0.2.0-alpha.2 installiert habe ist dieser Fehler bei einem bereits gespeicherten Steckbrief, der in der letzten Version erstellt wurde, aufgekommen. 
Als ich in den Bearbeitungsmodus gegangen bin und die dargestellten Texfelder "Ziele" und "Innerer Konflikt" gelöscht, den gleichen Text eingegeben und die Bearbeitung fertiggestellt habe wurde der Steckbrief wie erwartet angezeigt.

## Umgebung

- Plotify-Version: 0.2.0-alpha.2

- Betriebssystem: Ubuntu 16.04

**Comment by SebastianSchmidt** [comment]
Der Fehler kann nicht reproduziert werden. Eventuell wurde der Fehler bereits durch eine neue Version von Material-UI behoben.
