### ISSUE TITLE
Geschichte aus Dateimanager heraus öffnen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#70]
Als Schriftsteller/in möchte ich eine Geschichte direkt über deren Datei aus dem Dateimanager (z.B. Windows Explorer) öffnen können, um eine Geschichte direkt in Plotify bearbeiten zu können, ohne vorher Plotify gestartet haben zu müssen.

- [x] Windows
- [x] Linux
- [x] macOS

**Comment by SebastianSchmidt** [comment]
Erfolgreich getestet unter:
- Windows 7
- Ubuntu 17.04
- Linux Mint 18.1
- elementary OS 0.4

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Kannst du das Öffnen von Geschichten aus dem Dateimanager heraus unter Windows 10 und macOS testen?

**Comment by itsJASPERr** [comment]
Erfolgreich getestet unter:
* macOS High Sierra 10.13.1 (siehe #116)
* Windows 10 Version 1709
