### ISSUE TITLE
"Über Plotify" - Dialog

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#72]
Beim Klick auf den Menüpunkt "Über Plotify" soll nicht mehr die README auf GitHub geöffnet, sondern stattdessen ein Dialog geöffnet werden, in dem die folgenden Informationen dargestellt werden:

- [x] Name und Logo von Plotify.
- [x] Versionsnummer.
- [x] Kurze Beschreibung, wofür Plotify verwendet werden kann.
- [x] Auflistung der Mitwirkenden.
  - [x] Benutzeroberfläche implementieren.
  - [x] Profilbilder festlegen.
  - [x] Aufgaben/Rollen dokumentieren.
- [x] Lizenz von Plotify.
- [x] Lizenzen von Abhängigkeiten.
  - [x] Abhängigkeiten für Produktion
  - [x] Abhängigkeiten für Entwicklung
- [x] Fehler beheben: #136

**Comment by SebastianSchmidt** [comment]
Ich habe einen ersten Entwurf für den "Über Plotify"-Dialog erstellt:

![about-dialog-1](https://cloud.githubusercontent.com/assets/5047293/25500411/3e6e6f4a-2b8f-11e7-9a1c-6630e4ac36b7.png)

Nach einem Klick auf den Button "Mitwirkende" wird der folgende Dialog geöffnet:

![about-dialog-2](https://cloud.githubusercontent.com/assets/5047293/25500420/465ad7f2-2b8f-11e7-8558-934cc54693c5.png)

Nach einem Klick auf den Button "Lizenz" wird der folgende Dialog geöffnet:

![about-dialog-3](https://cloud.githubusercontent.com/assets/5047293/25500423/498ac3ce-2b8f-11e7-9904-253450dc8050.png)

Der vollständige Lizenztext soll in einem scrollbaren Textfeld angezeigt werden.

**Comment by itsJASPERr** [comment]
Aktueller Stand wird im Zuge von #84 Refactoring der UI mit umgezogen
