### ISSUE TITLE
Charakterliste flackert

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#75]
Beim jedem Update der Oberfläche flackert die Charakterliste.

Offensichtlich reproduzierbar durch häufiges Klicken auf den Hinzufügen -Button.

**Comment by SebastianSchmidt** [comment]
Die Charakterliste flackert allgemein immer dann, wenn sie aktualisiert wird. Das scheint daran zu liegen, dass die Charakterliste beim Aktualisieren kurz geleert wird.

**Comment by SebastianSchmidt** [comment]
Das Flackern lässt sich durch eine kleinen Änderung im Reducer verhindern.

Vorher:
```javascript
function characters(state = [], action) {
  switch (action.type) {
    // ...
    case RECEIVE_CHARACTERS:
      return Object.assign([], state, action.payload);
    case REQUEST_CHARACTERS:
      return [];
    default:
      return state;
  }
}
```

Die Charakterliste wird so erst dann aktualisiert, wenn die Charaktere abgerufen wurden.

Nachher:
```javascript
function characters(state = [], action) {
  switch (action.type) {
    // ...
    case RECEIVE_CHARACTERS:
      return Object.assign([], action.payload);
    case REQUEST_CHARACTERS:
      return state;
    default:
      return state;
  }
}
```

**Comment by itsJASPERr** [comment]
Das Hinzufügen eines Charakters lässt die Liste weiterhin flackern. Bzw. wird der gesamte UI Thread geblockt.

**Comment by SebastianSchmidt** [comment]
Ich habe die Bearbeitung dieses Tickets zurückgestellt, bis das Refactoring der UI #84 abgeschlossen ist.

**Comment by itsJASPERr** [comment]
Kann auf dem Branch für #84 getestet werden

**Comment by SebastianSchmidt** [comment]
Da die Codebasis komplett neu geschrieben wurde, schließe ich dieses Issue. Der Fehler ist aufgrund von Problemen in der Struktur der alten Codebasis aufgetreten.
