### ISSUE TITLE
Änderungen am Charakter während aktivem Filter lädt die Liste ohne Filter

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#76]
Reproduzieren:
- Charakter anlegen
- Namen Eingeben: "John Doe"
- Filter aktivieren: "test" (keine Charaktere in der Liste)
- Ein Feld des Charakters ändern
- Ergebnis: In der Liste erscheint der Charakter wieder, der Filter ist "noch aktiv"

**Comment by SebastianSchmidt** [comment]
Da die Codebasis komplett neu geschrieben wurde, schließe ich dieses Issue. Der Fehler ist aufgrund von Problemen in der Struktur der alten Codebasis aufgetreten.
