### ISSUE TITLE
QuickActions überleben Story-Wechsel

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#77]
Die QuickActions (Rückgängig, Wiederholen, ...) bleiben aktiv, wenn eine andere Geschichte geöffnet, oder eine neue erstellt wird.

**Comment by SebastianSchmidt** [comment]
Da die Codebasis komplett neu geschrieben wurde, schließe ich dieses Issue. Der Fehler ist aufgrund von Problemen in der Struktur der alten Codebasis aufgetreten.
