### ISSUE TITLE
Verzögerte Texteingabe beheben

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#79]
Bei den Textfeldern eines Charakters (Name und Steckbriefeinträge) erfolgt die Eingabe teilweise verzögert. Das bedeutet, dass nach dem Drücken einer Taste das jeweilige Zeichen mit einer kleinen Verzögerung in dem Textfeld erscheint. Diese Verzögerung sollte behoben werden, damit sich die Texteingabe flüssig anfühlt.

**Comment by itsJASPERr** [comment]
Ich vermute, dass dieses Problem mit dem verschachtelten State der Einträge zu tun hat. Da hier nicht einfach zwei Objekte gemerged werden können, sondern jedes mal über die Arrays iteriert werden muss, ist die State-Zusammenführung komplexer als sonst. 

`let stateCopy = Object.assign([], state);
      stateCopy.find((profile) => {
        return profile.id === action.payload.group_id;
      }).entries[action.payload.position]
        .value = action.payload.value;`

**Comment by SebastianSchmidt** [comment]
Dann sollten wir beim Refactoring des States darauf achten, solche Konstrukte zu vermeiden.Vielleicht muss der State auch nicht bei jedem Tastenanschlag geändert werden.

**Comment by SebastianSchmidt** [comment]
Da die Codebasis komplett neu geschrieben wurde, schließe ich dieses Issue. Die Verzögerungen bei der Texteingabe sind aufgrund von Problemen in der Struktur der alten Codebasis aufgetreten.
