### ISSUE TITLE
Application-Icon in der Programmliste von Windows anzeigen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#82]
In der Programmliste von Windows wird das Application-Icon von Plotify nicht angezeigt:

![Programmliste von Windows](https://cloud.githubusercontent.com/assets/5047293/25141727/b95280fc-2464-11e7-86a8-4d27963234ad.png)

**Comment by itsJASPERr** [comment]
liegt an der iconURL. Dort ist aktuell das auf Github liegende Logo angegeben. Scheinbar irgendetwas nicht korrekt

**Comment by SebastianSchmidt** [comment]
Problem wurde durch 673833f behoben.
