### ISSUE TITLE
Tabindex der Inputfelder korrigieren

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#83]
Wählt man einen Charakter aus und startet mit der Einstellung des Namens, so ist ist die Navigation in das nächste Textfeld durch das Drücken der Tabulator-Taste nicht möglich.

**Comment by itsJASPERr** [comment]
Kann auf dem Branch für #84 getestet werden

**Comment by SebastianSchmidt** [comment]
Der Fehler sollte im Rahmen des Tickets #112 behoben werden.

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Die Umsetzung der Animationen habe ich in das Ticket #129 verschoben.

**Comment by SebastianSchmidt** [comment]
Die Navigation durch die Felder ist nun wie gewünscht möglich.
