### ISSUE TITLE
Refactoring der UI

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#84]
Die technische Grundlage der Benutzeroberfläche soll überarbeitet werden.

Über die überarbeitete UI abgebildete Funktionen:
- [ ] WelcomePage
  - [x] Geschichte erstellen 
  - [x] Geschichte öffnen
  - [x] Neue Icons + Positionierung
  - [ ] Feedback 
    - [ ] ~~Ladeanzeige beim Öffnen und Erstellen~~
- [ ] CharacterPage 
  - [x] Charakterliste anzeigen
  - [x] Charakterliste filtern
  - [x] Charakter auswählen
  - [x] Charakter hinzufügen
  - [ ] Charakter bearbeiten
    - [x] Profil anzeigen
    - [ ] Name Fokussieren
    - [x] Gruppen + Einträge anzeigen
    - [ ] Rückgängig
      - [ ] Ein / Ausblenden
    - [ ] Wiederholen
      - [ ] Ein / Ausblenden
    - [x] AutoSave Entry
- [x] Burger Menu
  - [x] Geschichte erstellen 
  - [x] Geschichte öffnen 
  - [x] Speicherort öffnen
  - [x] About Dialog
- [ ] Snackbars
  - [x] Geschichte erstellen
    - [x] Fehler 
    - [x] Erfolg 
    - [x] Speicherort öffnen
  - [ ] ~~Geschichte geöffnet~~
    - [ ] ~~Fehler~~
    - [ ] ~~Erfolg~~
  - [ ] ~~Charakter ändern~~
    - [ ] ~~Erfolg~~
    - [ ] ~~Fehler~~

**Comment by SebastianSchmidt** [comment]
@itsJASPERr Beim Wechseln des ausgewählten Charakters wird der Charaktername im Profil aktuell nicht aktualisiert.

**Comment by itsJASPERr** [comment]
@SebastianSchmidt nun wieder 😄

**Comment by itsJASPERr** [comment]
Removing material-ui from the project now. Using mdl for now instead.

**Comment by itsJASPERr** [comment]
Die gesamte Funktionalität ist soweit wieder hergestellt, ohne material-ui. 
Bis auf den About-Dialog.

**Comment by SebastianSchmidt** [comment]
Anstatt eines Refactorings der UI findet ein kompletter Neuaufbau von Plotify statt.
