### ISSUE TITLE
Hinweis auf neue Versionen

### ISSUE THREAD

**Issue by SebastianSchmidt** [plotify/plotify#92]
Als Benutzer/in möchte ich darauf hingewiesen werden, wenn eine neue Version von Plotify zur Verfügung steht, damit ich zeitnah neue Funktionalitäten verwenden kann.

### Akzeptanzkriterien

- [x] Die Begriffe stabil (stable) und pre-release sollen gemäß [Semantic Versioning 2.0.0](https://semver.org/) verwendet werden.
- [x] Die Informationen über neue Versionen sind in einer JSON-Datei verfügbar, die über die folgende URL abgerufen werden kann: [https://plotify.org/releases/latest.json](https://plotify.org/releases/latest.json)
- [x] Die JSON-Datei ist über [OpenPGP](https://de.wikipedia.org/wiki/OpenPGP) digital signiert. Die digitale Signatur kann über die folgende URL abgerufen werden: [https://plotify.org/releases/latest.json.sig](https://plotify.org/releases/latest.json.sig)
- [x] Die digitale Signatur muss von einem bekannten öffentlichen Schlüssel stammen, der mit Plotify mitgeliefert wurde.
- [x] Die digitale Signatur ist der E-Mail-Adresse releases@plotify.org zugeordnet.
- [x] Wenn die digitale Signatur nicht verifiziert werden kann, wird der Inhalt der JSON-Datei nicht ausgewertet.
- [x] Wenn eine stabile Version installiert ist, soll nur auf neue stabile Versionen von Plotify hingewiesen werden.
- [x] Wenn eine pre-release Version installiert ist, soll auf die folgende neue Version hingewiesen werden:
      1. Wenn die letzte stabile Version höher als die letzte pre-release Version ist: Stabile Version
      2. Wenn die letzte pre-release Version höher als die letzte stabile Version ist und die letzte pre-release Version dieselbe Major.Minor.Patch-Version wie die installierte Version hat: Pre-release Version
      3. Wenn die letzte stabile Version niedriger als die letzte pre-release Version ist, aber 2. nicht der Fall ist: Stabile Version
- [x] Eine SNAPSHOT Version gilt weder als stabile, noch als pre-release Version. Wenn eine SNAPSHOT Version installiert ist, werden keine Hinweise auf neue Versionen angezeigt.
- [x] Die Informationen über neue Versionen werden abgerufen, nachdem das erste Fenster von Plotify vollständig geladen und angezeigt wurde.
- [x] Der Hinweis auf eine neue Version soll in Form einer [Snackbar](https://material.io/guidelines/components/snackbars-toasts.html) erscheinen, welche die folgenden Optionen bietet:
   - [x] Jetzt herunterladen: Öffnet die Download-Seite der neuen Version.
   - [x] Später: Der Hinweis auf eine neue Version wird beim nächsten Programmstart erneut angezeigt.
- [x] Der Hinweis auf eine neue Version wird in allen Fenstern angezeigt.
- [x] Wenn der Hinweis in einem Fenster geschlossen wurde, wird der Hinweis in allen anderen Fenstern ebenfalls geschlossen.

**Comment by SebastianSchmidt** [comment]
Der Changelog einer neuen Version liegt im Markdown-Format vor. Dieses könnte beispielsweise mit dem folgenden Parser in HTML konvertiert und angezeigt werden: [markdown-js
](https://github.com/evilstreak/markdown-js)

**Comment by SebastianSchmidt** [comment]
Markdown-js scheint nicht mehr aktiv weiter entwickelt zu werden. Die [letzte stabile Version von markdown-js](https://github.com/evilstreak/markdown-js/releases) wurde vor 4 Jahren veröffentlicht. Außerdem wird [HTML Code nicht korrekt behandelt](https://github.com/evilstreak/markdown-js/issues/288).

Eine Alternative ist die Bibliothek [markdown-it](https://github.com/markdown-it/markdown-it). Die [letze stabile Version](https://github.com/markdown-it/markdown-it/releases) wurde vor 2 Monaten veröffentlicht. Die Bibliothek scheint viel verwendet zu werden: Im letzten Monat wurde sie [laut NPM](https://www.npmjs.com/package/markdown-it) über 800.000 Mal heruntergeladen.

**Comment by SebastianSchmidt** [comment]
Um die Angriffsfläche zu reduzieren, soll der Changelog der neuen Version nicht in Plotify angezeigt werden.

**Comment by SebastianSchmidt** [comment]
Mögliche Varianten für den Aufbau der Snackbar:

![Variante 1](https://user-images.githubusercontent.com/5047293/35186569-8de005d4-fe16-11e7-9a86-5340ee3e1b66.png)

![Variante 2](https://user-images.githubusercontent.com/5047293/35186589-acf9b7c6-fe16-11e7-94b9-9b6d6c76c1d6.png)

**Comment by SebastianSchmidt** [comment]
[OpenPGP für JavaScript](https://github.com/openpgpjs/openpgpjs)

**Comment by itsJASPERr** [comment]
Für automatische Installation der neuen Version:

**Mounting von Volumes (macOS)**
1. gulp script run shell
2. Mount: `hdiutil attach ~/Downloads/plotify-0.2.0-alpha.2-macos-x64.dmg` 
3. Info über Volume sichern (output von Mount)
4. Öffnen: `open /Volumes/Plotify\ 0.2.0-alpha.2/`
5. Nutzer zieh in Applications Ordner
6. Unmount Volume `hdiutil detach /dev/disk2s1` (von 3.)

**Herausforderung**: Plotify muss während der Installation geschlossen sein. Das zur Installation gemountete Volume kann erst nach Installation, also nach dem Start von Plotify, unmountet werden.

**Comment by SebastianSchmidt** [comment]
Feature-Branch: [92-hinweis-neue-version](https://github.com/plotify/plotify/tree/92-hinweis-neue-version)

**Comment by SebastianSchmidt** [comment]
6dfc2bb: Workaround für https://github.com/electron/electron/issues/1833
