### ISSUE TITLE
Profiltextfelder zeigen Status

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#96]
Als Schriftsteller/in möchte ich, dass ein Status am Textfeld im Profil angezeigt wird, damit ich erkennen kann, wann meine Änderungen gespeichert werden; ob sie erfolgreich gespeichert wurden, oder ob ein Fehler beim Speichern aufgetreten ist. Somit bin ich immer über den aktuellen Stand meiner Änderungen informiert und fühle mich sicher in der Anwendung mit Plotify.

**Comment by itsJASPERr** [comment]
Speichert
![image](https://cloud.githubusercontent.com/assets/11521721/25917199/87dfbaa2-35c7-11e7-9669-5818a32a4755.png)

Erfolgreich (wird ausgeblendet nach X Sekunden)
![image](https://cloud.githubusercontent.com/assets/11521721/25917251/b4c7a2c8-35c7-11e7-80d0-574832e075b7.png)

Fehler
![image](https://cloud.githubusercontent.com/assets/11521721/25917259/bcf93e3e-35c7-11e7-998a-2c06a86c6511.png)

**Comment by SebastianSchmidt** [comment]
Der Status der Speichervorgänge soll nicht an den einzelnen Textfeldern angezeigt werden. Aktuell wird über eine Alternative nachgedacht, um dem Benutzer den Status der Speichervorgänge mitzuteilen.
