### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by BrinaPa** [plotify/plotify#97]
Ich habe nicht gerade viel Erfahren was Programmieren angeht, aber ich würde euch gerne Unterstützen und Helfen. Wen kann ich dafür am besten Kontaktieren?
Brina

**Comment by SebastianSchmidt** [comment]
Hallo Brina,
super, dass du dich an dem Projekt beteiligen möchtest! Wir freuen uns auf deine Hilfe! Ich würde dich gerne in unsere Chatgruppen einladen, damit wir uns besser absprechen können. Wie kann man dich am besten erreichen? Per E-Mail über deine Adresse im GitHub-Profil?

**Comment by BrinaPa** [comment]
Hallo Sebastian, 
Am besten über die E-Mail Adresse in meinem GitHub Profil, da bin ich auch am besten und schnellsten zu erreichen. Ich freue mich das ich euch unterstützen darf :)

**Comment by SebastianSchmidt** [comment]
Da die Kontaktaufnahme erfolgreich war schließe ich dieses Ticket.
