### ISSUE TITLE
Replace Redux with RxR-React

### ISSUE THREAD

**Issue by itsJASPERr** [plotify/plotify#99]
In Addition to refactoring the ui (#84) we realized very unintuitive performance issues seemingly resulting from the use of react-redux and perhaps not understanding it fully yet. Due to the effort already put into understanding it, we chose to try something else. 

See if the use of rxr-react (https://github.com/dacz/rxr-react) will improve performance of the ui and clarity in programming.

- [ ] Enhanced Performance
- [ ] Improved Clarity

**Comment by SebastianSchmidt** [comment]
Ich teste parallel eine andere Verwendung von React und Redux.

**Comment by itsJASPERr** [comment]
This has been done to a level where one was able to tell if it could be a better solution than redux.

It does not solve performance issues we had before. Those issures were due to the use of material-ui react framework.

Therefore, it is simply a matter of preference if we want to use redux or rxr (or none)
